server:
  port: 80
  servlet:
    contextPath: /activiti
spring:
  activiti:
    checkProcessDefinitions: false  #取消校验resources下的processes文件夹里的流程文件
    asyncExecutorEnabled: false
    job-executor-activate: true #开启JOB引擎
    database-schema:
    #flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。
    #true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
    #create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。
    #drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true
    jpa-enabled: false            #spring jpa使用
    #activiti rest 配置
    rest-api-enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_database?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#debug: true
#logging:
#  level:
#    org.activiti.engine.impl.persistence.entity: debug